### ISSUE TITLE
Código está correto!!!

### ISSUE THREAD

**Issue by glaucia86** [PauloAlves3486/projeto-xpto#1]
Paulo... dê uma olhada no cache conforme descrevi para ti no Linkedin e na resposta do vídeo para ti.
Caso dê problema (embora eu tenho certeza que não dará) me avise que eu faço um Screen Share contigo!

Abraços!

**Comment by PauloAlves3486** [comment]
Eu segui as suas orientações e funcionou, obrigado Glaucia!
